version: '3'

services:
  tomcat:
    image: tomcat:9.0.16-jre8
    volumes:
      - ./volumes/tomcat/webapps/jp.go.nict.langrid.webapps.composite-20181211.war:/usr/local/tomcat/webapps/langrid-composite-service.war
      - ./volumes/tomcat/conf/Catalina/localhost/langrid-composite-service-2.0.xml:/usr/local/tomcat/conf/Catalina/localhost/langrid-composite-service-2.0.xml
      - ./volumes/tomcat/logs:/usr/local/tomcat/logs
    ports:
      - "8081:8080"
      - "8010:8009"
    environment:
      TZ: Asia/Tokyo
